name: assignment
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Navigation & deep linking
  auto_route: ^10.0.1

  # Value equality check
  equatable: ^2.0.7

  # API requests
  dio: ^5.8.0+1

  # Dependency injection
  get_it: ^8.0.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.15

  # AutoRoute code generator
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true
